version: '3.8'

volumes:
  mongo_data:
    driver: local

services:
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:21.1.0
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command:
      - start-dev
    depends_on:
      - mongo

  mongo:
    container_name: mongo_db
    image: mongo
    restart: always
    volumes:
      - mongo_data:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: luisarce60089
      MONGO_INITDB_ROOT_PASSWORD: rGYwVKko8ihLmyaC